GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin_user;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA public TO write_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_user;


