GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_user;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO write_user;

GRANT ALL ON ALL TABLES IN SCHEMA public TO admin_user WITH GRANT OPTION;

